name: fast_blurhash
description: "A new Dart FFI package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0-114.0.dev

dependencies:
  cli_config: ^0.2.0
  logging: ^1.2.0
  native_assets_cli: ^0.7.1
  native_toolchain_c: ^0.5.2

dev_dependencies:
  ffi: ^2.1.2
  ffigen: ^12.0.0
  flutter_lints: ^4.0.0
  test: ^1.24.9
