name: fast_blurhash
description: "A high-performance Dart FFI package for decoding and encoding images using BlurHash, leveraging Rust for faster processing."
version: 0.0.1-dev.2
repository: https://github.com/Rahiche/fast_blurhash

environment:
  sdk: ^3.6.0-114.0.dev

dependencies:
  cli_config: ^0.2.0
  logging: ^1.2.0
  native_toolchain_rust: ^0.1.0-dev.6
  ffi: ^2.1.2
  ffigen: ^13.0.0


dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.24.9

